# Copyright (C) 2002-2024 CERN for the benefit of the ATLAS collaboration

# Name for this "action".
name: Build Tests

# Perform the builds on every push and pull request.
on: [ push, pull_request ]

# All the different build/test jobs.
jobs:

  # Containerised build jobs.
  container:

    # The different build modes to test.
    strategy:
      matrix:
        PLATFORM:
          - CONTAINER: "gitlab-registry.cern.ch/atlas/athena/analysisbase:24.2.36"
            OPTIONS:
          - CONTAINER: "gitlab-registry.cern.ch/atlas/athena/athanalysis:24.2.36"
            OPTIONS: -DATE_BASE_PROJECT=AthAnalysis
        BUILD:
          - TYPE: ["Debug", "Release"]

    # The system to run on.
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.PLATFORM.CONTAINER }}
      options: --user root

    # Use BASH as the shell from the image.
    defaults:
      run:
        shell: bash

    # The build/test steps to execute.
    steps:
    # Use a standard checkout of the code.
    - uses: actions/checkout@v2
    # Run the CMake configuration.
    - name: Configure
      run: |
        source /release_setup.sh
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.BUILD.TYPE }} ${{ matrix.PLATFORM.OPTIONS }} -S ${GITHUB_WORKSPACE} -B build
    # Perform the build.
    - name: Build
      run: |
        source /release_setup.sh
        cmake --build build
